### ISSUE TITLE
Caster fails to load with windows speech recognition engine

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/caster#305]
Caster fails to load with windows speech recognition engine. Using latest development branch and dragonfly 0.8.0
All applications failed to load similar to 'vscode'. and 'Attempting to load Caster ' continues indefinitely.

Truncated log
```
Ignoring application 'vscode'. Failed to load with:
(-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147200940), None)
(1) Attempting to load Caster -- WSR not loaded and listening yet...
(2) Attempting to load Caster -- WSR not loaded and listening yet...
```

Confirmation needed to label as a bug. Please test.
Simply close out Dragon NaturallySpeaking and double-click on `_caster.py`

**Comment by comodoro** [comment]
I can confirm: WSR starts turned off, applications fail to load and the `Attempting to load Caster` continues without user intervention. If I manually turn WSR on, it seems to start all right, but it has to be done really quickly before apps start to load.

**Comment by comodoro** [comment]
It seems doable to delay application load until user clicks the WSR button, but is this really the intended behavior? Should or shouldn't Dragonfly launch WSR without user intervention?

**Comment by LexiconCode** [comment]
> It seems doable to delay application load until user clicks the WSR button, but is this really the intended behavior? Should or shouldn't Dragonfly launch WSR without user intervention?

It is intended to launch WSR without user intervention.  A mechanism is in place already to load when WSR is available which needs to be debugged.

**Comment by LexiconCode** [comment]
@comodoro According to my testing I believe this issue has been fixed by https://github.com/Danesprite/dragonfly/commit/6d78fddacdc857e6c3d2ed971d9aee8a68a0e691

if you're willing to help test download from github the latest dragonfly repository and run from CMD or powershell `python setup.py install`.

**Comment by comodoro** [comment]
I can confirm now that it still does not work:) Thought actually that the problem might be on my side.

By the way, does the line https://github.com/synkarius/caster/blob/0c03ae2ab81fceb1c4421f2cf3e9cc6729a1ef43/_caster.py#L19 actually load all apps, not just firefox, because of __init__.py in apps? I cannot explain what i see in the console otherwise. Same goes for https://github.com/synkarius/caster/blob/0c03ae2ab81fceb1c4421f2cf3e9cc6729a1ef43/_caster.py#L12 and ccr rules.

**Comment by LexiconCode** [comment]
@comodoro  I can confirm the bug is not within caster. The issue is somewhere within dragonfly. See https://github.com/Danesprite/dragonfly/issues/41

The issue can be reproduced with sample.py which is a pure dragonfly implementation. On my machine the bug seems to be intermittent.

**Comment by LexiconCode** [comment]
I would have to look into that but I think you're correct about the init.py

**Comment by Danesprite** [comment]
Okay I've done a bit more looking into this. I still don't know how to fix it, but I noticed it also occurs with the original version of dragonfly. I don't think I'm familiar enough with Microsoft's Speech API to actually fix this. It could be specific to certain versions of Windows if no one has reported it before.

As @comodoro suggested on Gitter, we could just swap to using the `Sapi5InProcEngine` class. I get the sense from the old dragonfly issue on the topic that the class was supposed to replace the shared instance class anyway.

Given that there is no UI if `Sapi5InProcEngine` is used, I was thinking that a `RecognitionObserver` could print recognition results so there is at least some user feedback. The engine would need to be modified to notify observers of spoken words for that to work.

**Comment by LexiconCode** [comment]
SAPI 5's in-process engine class is the default in v0.11.0.

**Comment by LexiconCode** [comment]
T
